### ISSUE TITLE
How is V93K site control handled?

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen_testers#111]
Hi,

We found that on an older version of origen_testers that this was hard-coded to 'parallel'.  It doesn't seem to be that way on the latest version.  How can users control this?  Test method parameters?

thx

**Comment by ginty** [comment]
As far as I can tell it is still hardcoded to 'parallel', though this seems to be superseded by #114.

**Comment by info-rchitect** [comment]
@ginty yep decided to dive back in.
