### ISSUE TITLE
The avc_digcap_vpf method does not handle looping correctly

### ISSUE THREAD

**Issue by nxa09940** [Origen-SDK/origen_testers#145]
The avc_digcap_vpf method in lib/origen_testers/pattern_compilers/v93k.rb increments the capture_vectors variable by one for each appearance of the digcap.capture_string string. This does not take into account of vector looping which is used in the MTR bitmapping patterns. Suggest to change it as below:

      def avc_digcap_vpf(contents)
        capture_vectors = 0
        factor = 1
        contents.each_line do |line|
          next if line.match(/^\s*\#/)
          if line.match(/^\s*SQPG\s+LBGN\s+(\d+)\s*;/)
            factor = $1.to_i
          end
          factor = 1 if line.match(/^\s*SQPG\s+LEND\s*;/)
          capture_vectors += factor if /#{digcap.capture_string}/.match(line)
        end
        capture_vectors
      end

**Comment by ginty** [comment]
Thanks a lot for the patch, have you verified that this works correctly?

**Comment by nxa09940** [comment]
Yes, it is working in the K4F1 environment.

**Comment by rlaj** [comment]
nxa09940 says "Yes, it is working in the K4F1 environment."

**Comment by coreyeng** [comment]
Yes, this was verified internally.

**Comment by ginty** [comment]
Included in origen_testers version 0.45.1
