### ISSUE TITLE
sub-flows to not seem to know they are sub-flows

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen_testers#155]
Hi,

I am seeing an issue where sub-slows seem to think they are named the same as the parent flow file they were called from.

~~~ruby
From: /users/user/origen_testers/program/_erase.rb @ line 12 :

    10: Flow.create do |options|
    11:
 => 12:   binding.pry
    13:
    14:   # Define default options
    15:   options = { :pulses      => 4,
    16:               :post_verify => true,
    17:               :number => 0,

[1] pry(#<OrigenTesters::Test::Interface>)> flow.top_level?
=> true
[2] pry(#<OrigenTesters::Test::Interface>)> flow.name
=> :prb1
~~~

I was expecting the following behavior.

~~~ruby
[1] pry(#<OrigenTesters::Test::Interface>)> flow.top_level?
=> false
[2] pry(#<OrigenTesters::Test::Interface>)> flow.name
=> :erase
~~~

Is this a bug?
~~~

**Comment by ginty** [comment]
The `flow` method returns a handle on the current top-level flow, so its not so much that the sub-flow has the wrong name, but rather you are not looking at the sub-flow object.
Having said that, I'm not sure how to get a handle on the current sub-flow, what do you want to do with it?

**Comment by info-rchitect** [comment]
> The flow method returns a handle to the current top-level flow, so it's not so much that the sub-flow has the wrong name, but rather you are not looking at the sub-flow object.
> Having said that, I'm not sure how to get a handle on the current sub-flow, what do you want to do with it?

We clone tests on the fly with our characterization API with an option to place them at the end of flow.  When the charz API  is called in a sub-flow these cloned tests get created multiple times causing duplicates.

**Comment by ginty** [comment]
Ok, well even if you could get a handle on the flow, I think it is a dead end for you, you're not going to find just some array that you can delete things from.
Probably need to look further upstream in your code to work out what it is doing to create duplicates and solve it there.
