### ISSUE TITLE
Add an option on origen_testers to disable handshake between match loop pattern and vb

### ISSUE THREAD

**Issue by hua-liu** [Origen-SDK/origen_testers#177]
By default, there is a feature on app to generate some vectors on match loop pattern, which would set counter and cpua flag. This is to make handshake possible with vb codes. 
(origen_testers->igxl_based_tester->ultrfalex.rb->handshake)
Currently, on c40asf nvm development, there is no real operation on corresponding vb codes when cpuA flagged. C40asf nvm is running okay on line. And it also seems impossible to get the previous pattern result on vb, as ultraflex thinks the main module and subrountine as one burst result.

I manually remove handshake vectors on match loop pattern and update instances with cpuA off for c40asf, and verify it on line. There is huge test time saving I find. As to remove this handshake would affect overall patterns and flows' execution.

So I want to ask some help from Origen core team, to make it optional to enable/disable the handshake on match loop pattern generation.

Thanks a lot!
Hua

**Comment by pderouen** [comment]
@hua-liu you should be able to create a fork of this repository, make the updates you'd like, and submit a pull request. I'd recommend first creating a test case that expects your desired output and then update the code to produce that output.

I'd be happy to help you with the updates, or perhaps @redxeth could help as well.

**Comment by redxeth** [comment]
@hua-liu  yes I can help as well.  Do you feel confident to try as @pderouen suggests and fork the repository and make some changes yourself?

**Comment by hua-liu** [comment]
Thanks @redxeth @pderouen ! When I really clone the "origen_testers", and think about how to update it. Then I realize there is already an option for what I want. "check_for_fails" on match_block definition. (lib\origen_testers\igxl_based_tester\ultraflex.rb)
I think team already consider it when develop this feature.
Sorry, I should review it more carefully before I submit a ticket. 😂
Thank you! And it is ready to close this ticket!
