### ISSUE TITLE
Characterization inserts into J750 flow incorrectly if used in conditional block

### ISSUE THREAD

**Issue by rlaj** [Origen-SDK/origen_testers#20]
Using :cz_setup options within conditional block results in double flow line (one line with test instance having 'Test' opcode and one line with cz_setup having 'characterization' opcode).

Test case:
-------------------------------------
    if_enable 'usb_xcvr_cz' do
        func :xcvr_fs_vilvih, cz_setup: 'usb_fs_vil_cz'
        func :xcvr_fs_vilvih, cz_setup: 'usb_fs_vih_cz'
    end

Produces (incorrectly):
    		usb_xcvr_cz				Test	usb_xcvr_fs_vilvih_ti
    		usb_xcvr_cz				characterize	 usb_fs_vil_cz
    		usb_xcvr_cz				Test	usb_xcvr_fs_vilvih_ti
    		usb_xcvr_cz				characterize	 usb_fs_vih_cz

--------------------------------------
    func :xcvr_fs_vilvih, cz_setup: 'usb_fs_vil_cz', if_enable: 'usb_xcvr_cz'
    func :xcvr_fs_vilvih, cz_setup: 'usb_fs_vih_cz', if_enable: 'usb_xcvr_cz'

Produces (correctly):
    		usb_xcvr_cz				characterize	usb_xcvr_fs_vilvih_ti usb_fs_vil_cz
    		usb_xcvr_cz				characterize	usb_xcvr_fs_vilvih_ti usb_fs_vih_cz

**Comment by ginty** [comment]
Fixed in 0.7.11
