### ISSUE TITLE
Tester plugin does not currently support the generation of subroutine pattern modules

### ISSUE THREAD

**Issue by jiangliu23** [Origen-SDK/origen_testers#31]
Hi, one of the very useful features on ULTRALFEX is the ability to have multiple pattern modules within the same pattern, especially when it comes to the Subroutine Memory usage, by having the ability for user to create each global subroutine as an independent srm pattern module, it allows the tester to dynmaically swap the subroutine memories during run-time without bursting the maximum allowed SRM.

**Comment by redxeth** [comment]
Added in release 0.9.2.
