### ISSUE TITLE
[JLINK] Error is generating nvm_bistcom pattern. Singleton can't be dumped Error. 

### ISSUE THREAD

**Issue by austinsjc** [Origen-SDK/origen_testers#48]
All other environment (v93k, uflex) are working except jlink. 
Here is the errors:

..dev15/target 2813$ origen g nvm_bistcom_nosrc
[WARNING]    0.008[0.008]    || RGenScg: SCG does not have a parameter: base_address
[WARNING]    0.008[0.000]    || RGenScg: Parameter has_fll's group : was not found in the available groups!
Import Via SSDS
[INFO]       0.249[0.132]    || TDI_ID functionality disabled!
[INFO]       0.258[0.009]    || **********************************************************************
[INFO]       0.308[0.049]    || Generating...  /proj/.tec_s32m/users/kslau/ORIGEN/dbg_dev/dev15/output/nvm/patterns_no_tdi_id/nvm_bistcom_nosrc_debug.jlk

COMPLETE CALL STACK
-------------------
singleton can't be dumped
/home/b34335/.origen/gems/ruby/2.3.0/bundler/gems/c90tfs_nvm_tester-2a57f183efcd/lib/c90tfs_nvm_tester/parameters.rb:142:in `dump'
/home/b34335/.origen/gems/ruby/2.3.0/bundler/gems/c90tfs_nvm_tester-2a57f183efcd/lib/c90tfs_nvm_tester/parameters.rb:142:in `define_params'
/home/b34335/.origen/gems/ruby/2.3.0/bundler/gems/c90tfs_nvm_tester-2a57f183efcd/lib/c90tfs_nvm_tester/parameters/test_parameters.rb:159:in `instantiate_param_sets'
/home/b34335/.origen/gems/ruby/2.3.0/bundler/gems/c90tfs_nvm_tester-2a57f183efcd/lib/c90tfs_nvm_tester/parameters/test_parameters.rb:150:in `instantiate_test_params'
/home/b34335/.origen/gems/ruby/2.3.0/bundler/gems/c90tfs_nvm_tester-2a57f183efcd/lib/c90tfs_nvm_tester/parameters/default_parameters.rb:550:in `initialize'

Any idea ?

-KS

**Comment by ginty** [comment]
I don't think this is related to an Origen issue, and is more likely to be something to do with this particular application.

Please follow up with me internally if this is still a problem.

Thanks!
