### ISSUE TITLE
[j750] Combined if_failed flag issue

### ISSUE THREAD

**Issue by RobKang3** [Origen-SDK/origen_testers#76]
A combined if_failed flag will be generated if two if_failed flags used. And the  flag-true/false will be shown in Opcode column and the combined name in Parameter column. It can not been regonized in J750 unless set it with default at the start of test program. 
@ginty @redxeth 
![1](https://user-images.githubusercontent.com/35755488/35315786-32654590-00c6-11e8-8134-3e8f9e0619aa.jpg)
![2](https://user-images.githubusercontent.com/35755488/35315792-39d110d4-00c6-11e8-9123-73420029884c.jpg)

**Comment by ginty** [comment]
Thanks for the bug report @RobKang3.

Before I investigate further, could you confirm if this is still an issue on the latest version of OrigenTesters (0.15.0).

We have seen this kind of thing before and the injection of a default line was added - so its worth checking to see if this is already fixed in latest, or if we have a case here which it currently doesn't handle properly.

Thanks!

**Comment by ThaoHuynhFsl** [comment]
Hi Stephen:  We are still using 0.11.1.  The new OrigenTester that insert the default line to setup the default state for the flag will fixed the issue.  What is the atp gem version associate with the OrigenTester (0.15.0)?

**Comment by redxeth** [comment]
@ginty I can help here locally if it turns out that the latest version doesn't help.

**Comment by pderouen** [comment]
https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOrigen-SDK%2Forigen_testers%2Fissues%2F76%23issuecomment-360212601&data=02%7C01%7Cpaul.derouen%40nxp.com%7Cace37beeea1e46aab3de08d56350cbc9%7C686ea1d3bc2b4c6fa92cd99c5c301635%7C0%7C0%7C636524121020516180&sdata=NBDmUOQ3WjEjwl0OSLHpzxjZkN0aQkzMcqZ0a3%2FZSDo%3D&reserved=0

**Comment by ginty** [comment]
@ThaoHuynhFsl, your app shouldn't specify a version of atp since it is not a direct dependency, leave that to origen testers to pull in the version that it needs.

**Comment by ginty** [comment]
Could someone post a code snippet here that will show the problem?

**Comment by RobKang3** [comment]
Hi Stephen,
I have trial run this and it could work.
Would u pls help to send a tag to update into app?

**Comment by ginty** [comment]
OK @RobKang3, just released 0.16.0.
