### ISSUE TITLE
tester.dont_compress is not working

### ISSUE THREAD

**Issue by williamcheong** [Origen-SDK/origen_testers#95]
The syntax tester.dont_compress is not expand the vectors in generated atp.

for example, syntax below in use:
     `tester.cycle(repeat: 1000,dont_compress: true)`

It generated atp with opcode "repeat 1000".

If the dont_compress remain false or set to false, the opcode will be "repeat 1001". Make sense that the repeat integrated with the previous vector along.

It suppose to be fully expand until 1000 individual lines of vectors with same pin states without repeat.
Please help. Thanks.
version Origen: 0.33.1

**Comment by ginty** [comment]
Hi @williamcheong, thanks for reporting this. From reading your description I see what is going on now.

There is a misunderstanding here about what "dont_compress" means.

It means don't compress the pattern by looking for opportunities to create additional repeats that the application did not use when defining the vector cycles.

However, it does not mean un-roll all repeats that were already present in the way that the vectors were originally defined - and there is currently no switch to do that.

So your observations show this working correctly, if you have this:

~~~ruby
tester.cycle
tester.cycle repeat: 1000
~~~

Then by default Origen will recognize that there is an opportunity here to save a vector by compressing those into a single vector with repeat 1001.

If you have this:

~~~ruby
tester.cycle
tester.cycle repeat: 1000, dont_compress: true
~~~

Then Origen will note that you have requested for the repeat 1000 vector not to be involved in further compression and you will see that be generated as two vectors, one with a repeat 1 and one with a repeat 1000.

The intended use case of dont_compress is mainly for cases where you want to generate vectors which you might want to overlay later.

For example say you have this:

~~~ruby
# Serially write the register data
reg.shift_out_left do |bit|
  pin(:tdi).drive!(bit.data)
end
~~~

Normally, you want Origen to make the number of vectors involved in such a serial shift to be compressed/optimized to reduce the number of vectors.

However, if you want to modify the data at runtime (overlay it), then you don't want the vectors in the original pattern to be compressed based on the data value that was present at generation time.

It was for this reason we added the `dont_compress` feature:

~~~ruby
# Serially write the register data
tester.dont_compress = options[:overlay_data]  # Don't compress if we want to modify these vectors at runtime
reg.shift_out_left do |bit|
  pin(:tdi).drive!(bit.data)
end
tester.dont_compress = false # Turn compression back on
~~~

**Comment by ginty** [comment]
Closing this as it seems to be working correctly
