### ISSUE TITLE
Could we get a release that fixes the deprecation warning?

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen_testers#96]
Hi,

I am arranging some mass training and would the like deprecation warning gone so there are less things for trainees to ask me about.  I believe the fix is in the new SmarTest8 branch.

thx

~~~shell
[DEPRECATED] 9.071[0.017]    || Origen core will no longer support program generation in v1, add the origen_testers plugin to your application to fix this warning
[DEPRECATED] 9.072[0.001]    || Called by /users/bcaqueli/origen/aritp/ppekit/program/ringosc_flow.rb:1
~~~

**Comment by info-rchitect** [comment]
@ginty so this issue and [this issue](https://github.com/Origen-SDK/origen/issues/264) should be closed?

**Comment by ginty** [comment]
Yes please

**Comment by info-rchitect** [comment]
@Ginty but we are still seeing this in Origen 34.2 with the following in our Gemfile:

~~~ruby
gem 'origen_testers', git: 'ssh://git@stash.company.com:7999/osdk/origen_testers.git'
~~~

I must be confused, can you see what I am missing?

**Comment by ginty** [comment]
Not sure, but Origen 0.33.3 is the latest, so not sure what your version
reference it's to.

Note that the required update is part of Origen, not Origen testers.
