### ISSUE TITLE
Flow snippets in a test interface

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen_testers#98]
Hi,

We are starting to refactor our test interface after round 1 of on the job testing and came to the conclusion that we really need the ability to keep track of optional flow 'snippets' that could get added to a particular test.  For example, adding in alarm checks, adding in charz tests, etc.  These flow snippets would be run-time created tests that do not show up explicitly in the test flow file, rather they are added via API or test level options.  We currently handle this by making on-fail procs or by re-calling the test interface.  But it seems to me that their should be a better way to handle this activity.  Here is an example of some of the tests we create on the fly with our charz API:

![image](https://user-images.githubusercontent.com/26782653/44151168-57cadf02-a067-11e8-8aff-4be4f32ae21b.png)

- Should test interfaces add on directly to the ATP flow object or should Origen natively support adding to the ATP via another API?
- Or is there another way completely that we are missing?
- Does the ATP model need to understand test groups or does it already?

thx

**Comment by ginty** [comment]
The intention is that all test creation should be going via interface methods:

~~~ruby
# In the flow
func :my_test, blah: :blah

# In the interface
def func(pattern, options = {})
   
end
~~~

That architecture naturally enables you to inject anything you want into tests, even additional tests:

~~~ruby
def func(pattern, options = {})
  if add_alarm_block
    options[:on_fail] = -> {
      test :alarm_test
    }
  end
  
  # Code to create your test method etc, here

  test tm

  # Kick off additional tests everytime you call func
  if run_tests_twice
    test tm
  end
end
~~~

You can obviously re-factor that however you like to make snippets like the on_fail thing available to other test types.

To me, the architecture already supports the ability to do what you want here, and actually we already do things just like that in some of our apps.

The ATP model is the only way that information will be passed downstream to the individual ATE generators, so it has to go in there one way or the other.

ATP It should already understand groups just fine.

**Comment by ginty** [comment]
Just by chance, this is a little bit related - https://github.com/Origen-SDK/origen_testers/pull/99
